### ISSUE TITLE
使用 rem 单位的 font 属性不能简写

### ISSUE THREAD

**Issue by ibafly** [ibafly/blog#1]
在 html 标签里定义了含 calc 并混合 px 和 vw 单位后，其他使用 rem 的 font 属性简写时 pixrem 会报错：
Root font-size is invalid
如：
```css
html {
  font-size: calc(.5vw+14px);
}
/* 简写不可 */
h1 {
  font: 1.6rem/2 Arial;
}
```
根字号若仅为 vw 单位，没有问题。
目前不知道是 pixrem 需要配置还是它本身不支持这种混写的根字号，记录一下作约定和备忘。
